## Objective

- Start with 2 independent vectors a and b
- find orthonormal vectors q1 and q2 that span the same plane
- find orthogonal vectors first A, B

**Orthogonal Vectors**: if their dot product is 0

**Orthonormal Vectors**: if their dot product is 0 and their lengths are 1

In [1]:
import numpy as np

In [9]:
# a
a = np.array([[1, 2, 4],
              [4, 6, 9]])
print(a, a.shape)

# b
b = np.random.randint(low=0,high=10, size=(2,3))
print(b, b.shape)

[[1 2 4]
 [4 6 9]] (2, 3)
[[5 7 8]
 [1 8 7]] (2, 3)


$$
A=a \\ \\
B = b- \frac{A^Tb}{A^TA}A
$$

In [35]:
a = np.array([1,1,1])
b = np.array([1,0,2])
print(a.shape, b.shape)

(3,) (3,)


Finding orthogonal vectors

In [36]:
def getB(A, b):
    
    num = np.dot(A.T, b)
    den = np.dot(A.T, A)
    frac = num/den 
    B = b - np.dot(frac, A)
    return B

In [38]:
A = a 
B = getB(A, b)
print(f'A:\n{A},\nB:\n{B}')

A:
[1 1 1],
B:
[ 0. -1.  1.]


In [53]:
dot_product = np.dot(A, B)
print(f'Since dot product is {dot_product}, they are orthogonal!')

# length of vector
len_A = np.linalg.norm(A, ord=2)
len_B = np.linalg.norm(B, ord=2)
print(f'Length of A is {len_A}\nLength of B is {len_B}')

Since dot product is 0.0, they are orthogonal!
Length of A is 1.7320508075688772
Length of B is 1.4142135623730951


#### Since the dot product is 0, they are orthogonal. But, since the lengths of A and B vectors are not 1, they are not orthonormal!

In [65]:
A/np.linalg.norm(A, ord=2), np.linalg.norm(A/np.linalg.norm(A, ord=2), ord=2)

(array([0.57735027, 0.57735027, 0.57735027]), 1.0)

$$
Q1 = \frac{A}{||A||} \\
Q2 = \frac{B}{||B||}
$$

In [66]:
# getting orthonormal vectors 
def getQ(A, B):
    return A/np.linalg.norm(A, ord=2), B/np.linalg.norm(B, ord=2)

In [68]:
Q1, Q2 = getQ(A, B)

print(f'Q1:\n{Q1},\nQ2:\n{Q2}')

Q1:
[0.57735027 0.57735027 0.57735027],
Q2:
[ 0.         -0.70710678  0.70710678]


In [69]:
dot_product = np.round(np.dot(Q1, Q2), decimals=3)
print(f'Since dot product is {dot_product}, they are orthogonal!')

# length of vector
len_Q1 = np.round(np.linalg.norm(Q1, ord=2), decimals=3)
len_Q2 = np.round(np.linalg.norm(Q2, ord=2), decimals=3)
print(f'Length of Q1 is {len_Q1}\nLength of Q2 is {len_Q2}')

Since dot product is 0.0, they are orthogonal!
Length of Q1 is 1.0
Length of Q2 is 1.0


### Hence, the outputs Q1 and Q2 are the orthonormal vectors achieved from Gram-Schmidt Algorithm.

In [70]:
len_Q1 = np.linalg.norm(Q1, ord=2)
len_Q2 = np.linalg.norm(Q2, ord=2)
print(f'Length of Q1 is {len_Q1}\nLength of Q2 is {len_Q2}')

Length of Q1 is 1.0
Length of Q2 is 0.9999999999999999


### References:

- [Orthogonal Matrices: MIT Linear Algebra 2017 ](https://ocw.mit.edu/courses/18-06sc-linear-algebra-fall-2011/7ac32be444c25e48590f47573833ccc6_MIT18_06SCF11_Ses2.4sum.pdf)
- [Orthogonal and Orthonormal Vectors: James McCaffrey Wordpress](https://jamesmccaffrey.wordpress.com/2019/12/14/the-difference-between-orthogonal-and-orthonormal-vectors/)